CREATE OR REPLACE PROCEDURE RESTORE_STUDENTS_BY_LOGS(FROM_THIS_TIME DATE, TO_THIS_TIME DATE) IS
    CURSOR RECORDS_IN_LOGS IS
        SELECT *
        FROM STUDENTS_LOGS
        WHERE TIME_OF_COMMAND BETWEEN FROM_THIS_TIME AND TO_THIS_TIME
        ORDER BY TIME_OF_COMMAND DESC;
BEGIN
    EXECUTE IMMEDIATE 'ALTER TRIGGER STUDENTS_INSERT DISABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER STUDENTS_LOGS DISABLE';

    FOR ONE_RECORD IN RECORDS_IN_LOGS
        LOOP
            IF ONE_RECORD.COMMAND = 'INSERT' THEN
                DELETE FROM STUDENTS WHERE ID = ONE_RECORD.STUDENT_ID;
            ELSIF ONE_RECORD.COMMAND = 'UPDATE' THEN
                UPDATE STUDENTS
                SET NAME     = ONE_RECORD.OLD_NAME,
                    GROUP_ID = ONE_RECORD.OLD_GROUP_ID
                WHERE ID = ONE_RECORD.STUDENT_ID;
            ELSIF ONE_RECORD.COMMAND = 'DELETE' THEN
                INSERT INTO STUDENTS VALUES (ONE_RECORD.STUDENT_ID, ONE_RECORD.OLD_NAME, ONE_RECORD.OLD_GROUP_ID);
            END IF;
        END LOOP;
    EXECUTE IMMEDIATE 'ALTER TRIGGER STUDENTS_INSERT ENABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER STUDENTS_LOGS ENABLE';
END RESTORE_STUDENTS_BY_LOGS;