CREATE TABLE STUDENTS_LOGS
(
    STUDENT_ID      NUMBER,
    OLD_NAME        VARCHAR2(100),
    NEW_NAME        VARCHAR2(100),
    OLD_GROUP_ID    NUMBER,
    NEW_GROUP_ID    NUMBER,
    COMMAND         VARCHAR2(100),
    TIME_OF_COMMAND DATE
);



CREATE OR REPLACE TRIGGER STUDENTS_LOGS
    BEFORE INSERT OR UPDATE OR DELETE
    ON STUDENTS
    FOR EACH ROW
DECLARE
    PRAGMA AUTONOMOUS_TRANSACTION; -- FOR ROLLBACKS ETC
BEGIN
    IF INSERTING THEN
        INSERT INTO STUDENTS_LOGS VALUES (:NEW.ID, NULL, :NEW.NAME, NULL, :NEW.GROUP_ID, 'INSERT', SYSDATE);
    ELSIF UPDATING THEN
        INSERT INTO STUDENTS_LOGS
        VALUES (:OLD.ID, :OLD.NAME, :NEW.NAME, :OLD.GROUP_ID, :NEW.GROUP_ID, 'UPDATE', SYSDATE);
    ELSIF DELETING THEN
        INSERT INTO STUDENTS_LOGS VALUES (:OLD.ID, :OLD.NAME, NULL, :OLD.GROUP_ID, NULL, 'DELETE', SYSDATE);
    END IF;
    COMMIT;
END STUDENTS_LOGS;