CREATE TABLE STUDENTS
(
    ID NUMBER NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    GROUP_ID NUMBER NOT NULL
);

CREATE TABLE GROUPS
(
    ID NUMBER NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    C_VAL NUMBER NOT NULL
);