INSERT INTO GROUPS VALUES (3, 'NIGGERS', 0);

INSERT INTO GROUPS VALUES(2, 'NOTNIGGERS', 0);

SELECT * FROM GROUPS;

INSERT INTO STUDENTS VALUES (1, 'NIGGER', 1);
INSERT INTO STUDENTS VALUES (1, 'NOTNIGGER', 2);

SELECT * FROM STUDENTS;

DELETE FROM STUDENTS;

DELETE FROM GROUPS WHERE ID = 1;


SELECT * FROM STUDENTS_LOGS;

BEGIN
    RESTORE_STUDENTS_BY_LOGS(TO_DATE('2023-03-10 15:21:00','yyyy-mm-dd hh24:mi:ss'),TO_DATE('2023-03-10 15:21:59','yyyy-mm-dd hh24:mi:ss'));
END;

