INSERT INTO STUDENTS VALUES (1, 'NAME111', 1);
INSERT INTO STUDENTS VALUES (3, '3333333', 2);

SELECT * FROM STUDENTS;

DELETE FROM STUDENTS WHERE ID = 3;


SELECT * FROM GROUPS;

INSERT INTO GROUPS VALUES (2, 'NIGGERSS', 100);

DELETE FROM GROUPS WHERE ID = 2

