CREATE USER DEVELOPER IDENTIFIED BY PASSWORD;
CREATE USER PRODUCTOR IDENTIFIED BY PASSWORD;

GRANT CREATE TABLE TO DEVELOPER;
GRANT CREATE TABLE TO PRODUCTOR;

SELECT USERNAME, ACCOUNT_STATUS
FROM DBA_USERS
WHERE USERNAME = 'PRODUCTOR';

SELECT *
FROM PRODUCTOR.PERSONS;