CREATE USER DEVELOPER IDENTIFIED BY PASSWORD;
CREATE USER PRODUCTOR IDENTIFIED BY PASSWORD;

GRANT CREATE TABLE TO USER2;
GRANT CREATE TABLE TO PRODUCTOR;

GRANT CREATE PROCEDURE TO USER2;


SELECT USERNAME, ACCOUNT_STATUS
FROM DBA_USERS
WHERE USERNAME = 'PRODUCTOR';

GRANT ALL PRIVILEGES TO DEVELOPER;


CREATE OR REPLACE PROCEDURE TEST_PROCEDURE000(TMP1 NUMBER) IS
BEGIN
    NULL;
END TEST_PROCEDURE000;

-- CREATE OR REPLACE FUNCTION TEST_FUNCTION(TMP1 VARCHAR2) RETURN NUMBER IS
-- BEGIN
--     return 10;
-- END TEST_FUNCTION;