CREATE OR REPLACE PROCEDURE CHECK_TABLES(DEV_SCHEMA_NAME VARCHAR2, PROD_SCHEMA_NAME VARCHAR2) IS
    CURSOR TABLE_NAMES IS
        SELECT *
        FROM (SELECT TABLE_NAME DEVELOPER_TABLE_NAME FROM ALL_TABLES WHERE OWNER = UPPER(DEV_SCHEMA_NAME)) DEVELEPOER
                 FULL OUTER JOIN
             (SELECT TABLE_NAME PRODUCTOR_TABLE_NAME FROM ALL_TABLES WHERE OWNER = UPPER(PROD_SCHEMA_NAME)) PRODUCTOR
             ON DEVELEPOER.DEVELOPER_TABLE_NAME = PRODUCTOR.PRODUCTOR_TABLE_NAME;
BEGIN

    FOR RECORD IN TABLE_NAMES
        LOOP
            IF RECORD.DEVELOPER_TABLE_NAME IS NULL THEN
                DBMS_OUTPUT.PUT('NEED TO EXECUTE IN PRODUCTOR SCHEME: ');
                DBMS_OUTPUT.PUT_LINE('DROP TABLE ' || RECORD.PRODUCTOR_TABLE_NAME || ';');
                CONTINUE;
            END IF;


        END LOOP;

END CHECK_TABLES;

CREATE OR REPLACE PROCEDURE CHECK_TABLES_STRUCTURE(DEV_SCHEMA_NAME VARCHAR2, PROD_SCHEMA_NAME VARCHAR2,
                                                   TABLE_NAME_TO_CHECK VARCHAR2) IS
    CURSOR TABLE_COLUMNS IS
        SELECT *
        FROM (SELECT COLUMN_NAME DEVELOPER_COLUMN_NAME
              FROM ALL_TAB_COLUMNS
              WHERE OWNER = UPPER(DEV_SCHEMA_NAME)
                AND TABLE_NAME = UPPER(TABLE_NAME_TO_CHECK)) DEVELOPER
                 FULL OUTER JOIN
             (SELECT COLUMN_NAME PRODUCTOR_COLUMN_NAME
              FROM ALL_TAB_COLUMNS
              WHERE OWNER = UPPER(PROD_SCHEMA_NAME)
                AND TABLE_NAME = UPPER(TABLE_NAME_TO_CHECK)) PRODUCTOR
             ON DEVELOPER.DEVELOPER_COLUMN_NAME = PRODUCTOR.PRODUCTOR_COLUMN_NAME;
BEGIN
    FOR RECORD IN TABLE_COLUMNS
        LOOP

        END LOOP;
END CHECK_TABLES_STRUCTURE;



CREATE OR REPLACE PROCEDURE CHECK_SCHEMAS(DEV_SCHEMA_NAME VARCHAR2, PROD_SCHEMA_NAME VARCHAR2) IS
BEGIN
    CHECK_TABLES('DEVELOPER', 'PRODUCTOR');
END;

BEGIN
    CHECK_SCHEMAS('DEVELOPER', 'PRODUCTOR');
END;