SELECT *
FROM ALL_INDEXES
WHERE OWNER = 'DEVELOPER'
   OR OWNER = 'PRODUCTOR';

SELECT *
FROM ALL_IND_COLUMNS
WHERE INDEX_OWNER = 'DEVELOPER'
   OR INDEX_OWNER = 'PRODUCTOR';

SELECT *
FROM ALL_TABLES
WHERE OWNER = 'DEVELOPER';

SELECT *
FROM (SELECT TABLE_NAME DEVELOPER_NAME FROM ALL_TABLES WHERE OWNER = UPPER('DEVELOPER')) DEV
         FULL OUTER JOIN
     (SELECT TABLE_NAME PRODUCTOR_NAME FROM ALL_TABLES WHERE OWNER = UPPER('PRODUCTOR')) PROD
     ON DEV.DEVELOPER_NAME = PROD.PRODUCTOR_NAME;


SELECT TABLE_NAME DEVELOPER_NAME
FROM ALL_TABLES
WHERE OWNER = UPPER('DEVELOPER');

SELECT *
FROM ALL_CONSTRAINTS
WHERE OWNER = 'PRODUCTOR'
  AND TABLE_NAME = 'PERSONS'
  AND NOT REGEXP_LIKE(CONSTRAINT_NAME, '^SYS_C\d+');


SELECT *
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'DEVELOPER';

BEGIN
    IF 'NUMBER' != 'VARCHAR2' THEN
        DBMS_OUTPUT.PUT_LINE('MISMATCH OF DATA TYPE IN #' || ' #');
    END IF;
END;