SELECT *
FROM ALL_INDEXES
WHERE OWNER = 'DEVELOPER'
   OR OWNER = 'PRODUCTOR';

SELECT *
FROM ALL_IND_COLUMNS
WHERE INDEX_OWNER = 'DEVELOPER'
   OR INDEX_OWNER = 'PRODUCTOR';

SELECT *
FROM ALL_TABLES
WHERE OWNER = 'DEVELOPER';

SELECT *
FROM (SELECT TABLE_NAME DEVELOPER_NAME FROM ALL_TABLES WHERE OWNER = UPPER('DEVELOPER')) DEV
         FULL OUTER JOIN
     (SELECT TABLE_NAME PRODUCTOR_NAME FROM ALL_TABLES WHERE OWNER = UPPER('PRODUCTOR')) PROD
     ON DEV.DEVELOPER_NAME = PROD.PRODUCTOR_NAME;


SELECT TABLE_NAME DEVELOPER_NAME
FROM ALL_TABLES
WHERE OWNER = UPPER('DEVELOPER');

SELECT *
FROM ALL_CONSTRAINTS
WHERE OWNER = 'PRODUCTOR'
  AND TABLE_NAME = 'PERSONS'
  AND NOT REGEXP_LIKE(CONSTRAINT_NAME, '^SYS_C\d+');


SELECT *
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'DEVELOPER';

BEGIN
    IF 'NUMBER' != 'VARCHAR2' THEN
        DBMS_OUTPUT.PUT_LINE('MISMATCH OF DATA TYPE IN #' || ' #');
    END IF;
END;

SELECT *
FROM ALL_OBJECTS
WHERE OWNER = 'DEVELOPER'
  AND OBJECT_TYPE = 'FUNCTION';
SELECT *
FROM ALL_SOURCE
WHERE OWNER = 'DEVELOPER';

SELECT UPPER(TRIM(' ' FROM (TRANSLATE(text, CHR(10) || CHR(13), ' ')))) object_text
FROM all_source;

SELECT UPPER(TRIM(' ' FROM (TRANSLATE(text, CHR(10) || CHR(13), ' ')))) object_text
FROM all_source
WHERE owner = UPPER('DEVELOPER')
  AND name = UPPER('TEST_FUNCTION')
  AND type = UPPER('FUNCTION')
  AND text != chr(10);


SELECT *
FROM (SELECT OBJECT_NAME DEVELOPER_NAME
      FROM ALL_OBJECTS
      WHERE OWNER = UPPER('DEVELOPER')
        AND OBJECT_TYPE = UPPER('FUNCTION')) DEVELOPER
         FULL JOIN
     (SELECT OBJECT_NAME PRODUCTOR_NAME
      FROM ALL_OBJECTS
      WHERE OWNER = UPPER('PRODUCTOR')
        AND OBJECT_TYPE = UPPER('FUNCTION')) PRODUCTOR
     ON DEVELOPER.DEVELOPER_NAME = PRODUCTOR.PRODUCTOR_NAME;



SELECT *
FROM (SELECT CONSTRAINT_NAME DEVELOPER_CONSTRAINT_NAME
      FROM ALL_CONSTRAINTS
      WHERE OWNER = UPPER('DEVELOPER')
        AND TABLE_NAME = UPPER('PERSONS')
        AND NOT REGEXP_LIKE(CONSTRAINT_NAME, '^SYS_C\d+')) DEVELOPER
         FULL OUTER JOIN
     (SELECT CONSTRAINT_NAME PRODUCTOR_CONSTRAINT_NAME
      FROM ALL_CONSTRAINTS
      WHERE OWNER = UPPER('PRODUCTOR')
        AND TABLE_NAME = UPPER('PERSONS')
        AND NOT REGEXP_LIKE(CONSTRAINT_NAME, '^SYS_C\d+')) PRODUCTOR
     ON DEVELOPER.DEVELOPER_CONSTRAINT_NAME = PRODUCTOR.PRODUCTOR_CONSTRAINT_NAME;



SELECT DISTINCT NAME
FROM ALL_SOURCE
WHERE OWNER = 'DEVELOPER'
  AND TYPE = 'FUNCTION';


SELECT *
FROM (SELECT DISTINCT NAME DEVELOPER_NAME
      FROM ALL_SOURCE
      WHERE OWNER = UPPER('DEVELOPER')
        AND TYPE = UPPER('PROCEDURE')) DEVELOPER
         FULL JOIN
     (SELECT DISTINCT NAME PRODUCTOR_NAME
      FROM ALL_SOURCE
      WHERE OWNER = UPPER('PRODUCTION')
        AND TYPE = UPPER('PROCEDURE')) PRODUCTOR
     ON DEVELOPER.DEVELOPER_NAME = PRODUCTOR.PRODUCTOR_NAME;


SELECT UPPER(TRIM(' ' FROM (TRANSLATE(text, CHR(10) || CHR(13), ' ')))) object_text
FROM all_source
WHERE owner = UPPER('PRODUCTOR')
  AND type = UPPER('FUNCTION')
  AND text != chr(10);

SELECT *
FROM ALL_OBJECTS;

SELECT OBJECT_NAME

FROM ALL_OBJECTS
WHERE OWNER = UPPER('PRODUCTOR')
  AND OBJECT_TYPE = UPPER('FUNCTION');

SELECT *
FROM (SELECT OBJECT_NAME DEVELOPER_NAME
      FROM ALL_OBJECTS
      WHERE OWNER = UPPER('DEVELOPER')
        AND OBJECT_TYPE = UPPER('FUNCTION')) DEVELOPER
         FULL OUTER JOIN
     (SELECT OBJECT_NAME PRODUCTOR_NAME
      FROM ALL_OBJECTS
      WHERE OWNER = UPPER('PRODUCTOR')
        AND OBJECT_TYPE = UPPER('FUNCTION')) PRODUCTOR
     ON DEVELOPER.DEVELOPER_NAME = PRODUCTOR.PRODUCTOR_NAME;


SELECT *
FROM ALL_PROCEDURES
WHERE OBJECT_TYPE = 'FUNCTION';

SELECT * FROM ALL_USERS;


   SELECT OBJECT_NAME FROM ALL_OBJECTS WHERE OWNER = 'PRODUCTOR' AND OBJECT_TYPE = 'FUNCTION'
                             MINUS
                             SELECT OBJECT_NAME FROM ALL_OBJECTS WHERE OWNER = 'DEVELOPER' AND OBJECT_TYPE = 'FUNCTION';




SELECT *
        FROM (SELECT OBJECT_NAME
              FROM ALL_OBJECTS
              WHERE OWNER = 'PRODUCTOR'
                AND OBJECT_TYPE = 'FUNCTION'
              MINUS
              SELECT OBJECT_NAME
              FROM ALL_OBJECTS
              WHERE OWNER = 'DEVELOPER'
                AND OBJECT_TYPE = 'FUNCTION');

    DROP PROCEDURE CHECK_FUNCTIONS_OR_PROCEDURES;



   SELECT * FROM ALL_OBJECTS WHERE OBJECT_TYPE = 'PROCEDURE';


SELECT *
        FROM (SELECT OBJECT_NAME
              FROM ALL_OBJECTS
              WHERE OWNER = 'PRODUCTOR'
                AND OBJECT_TYPE = 'FUNCTION'
              MINUS
              SELECT OBJECT_NAME
              FROM ALL_OBJECTS
              WHERE OWNER = 'DEVELOPER'
                AND OBJECT_TYPE = 'FUNCTION');


SELECT TRIM(' ' FROM (TRANSLATE(ALL_SOURCE.TEXT, CHR(10) || CHR(13), ' '))) FROM ALL_SOURCE;